### ISSUE TITLE
Validation Error: Path 'password' required

### ISSUE THREAD

**Issue by sneakycr0w** [sneakycr0w/lotus#15]
After adding the password field + bcrypt I'm now receiving this error when trying to have passwords within the model. 

```
name: help@help.com, email: help
(node:20895) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
{ ValidationError: User validation failed: password: Path `password` is required.
    at ValidationError.inspect (/Users/zacharysohovich/git/lotus/node_modules/mongoose/lib/error/validation.js:57:23)
    at formatValue (util.js:372:36)
    at inspect (util.js:236:10)
    at format (util.js:97:24)
    at Console.log (console.js:113:24)
    at newUser.save.err (/Users/zacharysohovich/git/lotus/server.js:32:29)
    at /Users/zacharysohovich/git/lotus/node_modules/mongoose/lib/model.js:3919:16
    at /Users/zacharysohovich/git/lotus/node_modules/mongoose/lib/services/model/applyHooks.js:167:17
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  errors:
   { password:
      { ValidatorError: Path `password` is required.
          at ValidatorError (/Users/zacharysohovich/git/lotus/node_modules/mongoose/lib/error/validator.js:25:11)
          at validate (/Users/zacharysohovich/git/lotus/node_modules/mongoose/lib/schematype.js:758:13)
          at /Users/zacharysohovich/git/lotus/node_modules/mongoose/lib/schematype.js:805:11
          at Array.forEach (<anonymous>)
          at SchemaString.SchemaType.doValidate (/Users/zacharysohovich/git/lotus/node_modules/mongoose/lib/schematype.js:765:19)
          at /Users/zacharysohovich/git/lotus/node_modules/mongoose/lib/document.js:1506:9
          at _combinedTickCallback (internal/process/next_tick.js:131:7)
          at process._tickCallback (internal/process/next_tick.js:180:9)
        message: 'Path `password` is required.',
        name: 'ValidatorError',
        properties: [Object],
        kind: 'required',
        path: 'password',
        value: undefined,
        reason: undefined,
        '$isValidatorError': true } },
  _message: 'User validation failed',
  name: 'ValidationError' }
```

**Comment by sneakycr0w** [comment]
First half of the issue was resolved by @jorgenho (thanks dude) in 8e296b61e1539c046d6f3ebc9a239555c6b7610e which was axios not sending the password field. Second issue was react not giving axios the password field because I never establish a `name` attribute. I fixed this in 5ef1f7b24b54d49c4995a423f2891fd145536d72
